name: Snyk Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate Snyk
        run: snyk auth
        env:
          SNYK_TOKEN: ${{ secrets.Snyk }}

      - name: Run Snyk test
        run: snyk test || true
